-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 11:49:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_boutique
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_boutique` ;

-- -----------------------------------------------------
-- Schema bd_boutique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_boutique` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_boutique` ;

-- -----------------------------------------------------
-- Table `bd_boutique`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_boutique`.`categorie` ;

CREATE TABLE IF NOT EXISTS `bd_boutique`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorie_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_boutique`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_boutique`.`produit` ;

CREATE TABLE IF NOT EXISTS `bd_boutique`.`produit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produit_name` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  `prix` DECIMAL(10,2) NOT NULL,
  `url_image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produit_categorie_idx` (`categorie_id` ASC) VISIBLE,
  CONSTRAINT `fk_produit_categorie`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `bd_boutique`.`categorie` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_boutique`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_boutique`.`image` ;

CREATE TABLE IF NOT EXISTS `bd_boutique`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produit_id` INT NOT NULL,
  `url_image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_produit_idx` (`produit_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_produit`
    FOREIGN KEY (`produit_id`)
    REFERENCES `bd_boutique`.`produit` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_boutique`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_boutique`.`user` ;

CREATE TABLE IF NOT EXISTS `bd_boutique`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `adresse` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_boutique`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_boutique`.`order` ;

CREATE TABLE IF NOT EXISTS `bd_boutique`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `prix_total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bd_boutique`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_boutique`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_boutique`.`order_items` ;

CREATE TABLE IF NOT EXISTS `bd_boutique`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produit_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `prix_unitaire` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_order_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_items_produit_idx` (`produit_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `bd_boutique`.`order` (`id`),
  CONSTRAINT `fk_order_items_produit`
    FOREIGN KEY (`produit_id`)
    REFERENCES `bd_boutique`.`produit` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
